src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Date_Reported__c</fullName>
        <label>Date_Reported</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Date_Due</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GC1040</fullName>
                </value>
                <value>
                    <fullName>GC1060</fullName>
                </value>
                <value>
                    <fullName>GC3020</fullName>
                </value>
                <value>
                    <fullName>GC3040</fullName>
                </value>
                <value>
                    <fullName>GC3060</fullName>
                </value>
                <value>
                    <fullName>GC5020</fullName>
                </value>
                <value>
                    <fullName>GC5040</fullName>
                </value>
                <value>
                    <fullName>GC5060</fullName>
                </value>
                <value>
                    <fullName>GC1020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Vehicle__c.object
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Work_Part__c.object
<CustomObject>
    <fields>
        <fullName>Maintenance_Cycle__c</fullName>
        <label>Maintenance_Cycle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Work Parts</relationshipLabel>
        <relationshipName>Work_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Part</label>
    <nameField>
        <label>Work Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MaintenanceRequestHelper.cls
public with sharing class MaintenanceRequestHelper {
    public static void updateWorkOrders(Map<Id,Case> applicableCases){
    	//Variables for product and cases.
    	Map<Id,Integer> mapProduct = new Map<Id,Integer>();
    	List<Case> newCases = new List<Case>();
    	
    	//Product list having Id and maintenance cycle value. 
    	List<Work_Part__c> listProduct = [SELECT Id, Maintenance_Cycle__c FROM Work_Part__c];
    	for(Work_Part__c p : listProduct){
    		if(p != null){
    			if(p.Maintenance_Cycle__c != null){
    				mapProduct.put(p.Id,Integer.valueOf(p.Maintenance_Cycle__c));
    			}
    		}
    	}
    	
    	//For Every Case update the values and request for maintenance
    	for(Case aCase : applicableCases.values()){
    		Case newCase = new Case();
    		newCase.Vehicle__c = aCase.Vehicle__c;
    		newCase.Type = 'Routine Maintenance';
            newCase.Subject = String.isBlank(aCase.Subject) ? 'Routine Maintenance Request' : aCase.Subject;
            newCase.Date_Reported__c = Date.today();
            newCase.Status = 'New';
            newCase.Product__c = aCase.Product__c;
            newCase.Due_Date__c =  (mapProduct.get(aCase.Id) != null) ? (Date.today().addDays(Integer.valueOf(mapProduct.get(aCase.Id)))) : (Date.today());
            newCases.add(newCase);
    	}
    	if(newCases.size() > 0){
    		insert newCases;
    	}
    }
}